#! /bin/bash
killall evince
filename=`basename ${1}`
if [[ ${filename} != *.tex ]]
then
    filename=${filename}tex
fi
cd tex
pdflatex ${filename} 
mv ${filename/\.tex/\.pdf} ../
cd ..
evince ${filename/\.tex/\.pdf} &
